#! /bin/sh
cmd=$1
package_name=$2

LIST_FILE=~/.go_pkg_list

usage() {
    echo "Usage:"    
}

list() {
    cat $LIST_FILE
}

update() {
    if ! grep -q $1 $LIST_FILE && [[ $1 != "all" ]]; then
        echo "package:$1 doesn't exist"
        exit 1
    fi
    case $1 in
        all)
            for pkg in `cat $LIST_FILE`; do
                update $pkg
            done
            ;;
        *)
            echo "update package:$1"
            go get -u $1
            ;;
    esac
}

get() {
    if grep -q $1 $LIST_FILE; then
        update $1
    else
        echo "get $1"
        go get $1 && echo $1 >> $LIST_FILE
    fi
}

case $cmd in
    get)
        get $2
        ;;
    update)
        update $2
        ;;
    list)
        list
        ;;
    *)
        usage
        ;;
esac
